title: Designer Byeonsungmin Portfolio
author: Byeon sungmin
email: e2yser@naver.com
description:
  안녕하세요. 제안서·그래픽 디자이너 변성민입니다.
  <p>전문적인 그래픽 및 제안서 디자이너로서, 색다른 시각으로 기업의 핵심 가치를 효과적으로 표현하고 있습니다.<br>
  디자인으로 기업의 전문성을 강조하며, 프로젝트 제안서를 통해 명확하게 비즈니스 가치를 전달하고 있습니다.</p>
social:
  facebook:
  instagram:
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
